name: Increment Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  increment_version:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Increment version
      run: uv version --bump patch

    - name: Commit and push
      run: |
        git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pyproject.toml uv.lock
        git commit -m "Increment version" || echo "No changes"
        git push

    - name: Notify discord
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
